### PR TITLE
Fix Arc Thrower code

### PR DESCRIPTION
**Pull request by fungilation**
See https://game8.co/games/Helldivers-2/archives/446541

### CODE REVIEW

**Comment by spyoungtech** [comment]
Thanks!

**Comment by fungilation** [comment]
cool. What's your workflow for making releases together with version bump? I'm new to python

**Comment by spyoungtech** [comment]
@fungilation  The basic release process is as follows:

1. Update the version number [in `setup.cfg`](https://github.com/spyoungtech/helldivers2-macros/blob/f30cdd60a14c22559c6d618055207da1cf0c84f3/setup.cfg#L4) (for the PyPI release) and [in `inno.iss`](https://github.com/spyoungtech/helldivers2-macros/blob/f30cdd60a14c22559c6d618055207da1cf0c84f3/inno.iss#L5) (for the compiled zip/setup releases)
2. I create a GitHub release (which also creates a tag) that triggers the [GitHub Action workflow](https://github.com/spyoungtech/helldivers2-macros/blob/main/.github/workflows/release.yaml). This builds the various distributions and uploads them to PyPI and the GitHub release page.

I'll get around to doing this later today :)

But if you were wanting to build/compile the project yourself, you can use the GitHub Actions workflow as a guide. I may also document the instructions in the repo in the future.

**Comment by fungilation** [comment]
thanks. I'm kinda learning python ecosystem as well with this.

I got manual compile working with just pyinstaller alone

**Pull request merged**
